### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by tildebyte** [Dhar/image-dreamer#10]
This isn't technically a question for this project, but I can't even figure out where the exceedingly verbose logging is _coming_ from, e.g. about a million lines of
`I0716 14:38:20.613493  2857 net.cpp:194] foo_bar_baz wonk`.

**Comment by Dhar** [comment]
In that example, the "net.cpp:194" tells you it's being logged from line 194 of some file "net.cpp".  Of course, that's probably in some lower-level library that would be a pain to change.

**Comment by tildebyte** [comment]
I figured. I just didn't feel like grepping through all of the sources of all of the packages involved :laughing: 
I suspect it may be in google proto.
I guess I was hoping that you might know of a secret switch to pass in somewhere to quiet down whatever library it is :wink:

**Comment by tildebyte** [comment]
Nope, `glog`. I don't see offhand how to drop the verbosity short of re-compiling, but

```
minloglevel (int, default=0, which is INFO)
    Log messages at or above this level. Again, the numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively.

```

in the environment works great (e.g. for `bash`, `export GLOG_minloglevel=2`)
