### ISSUE TITLE
Check failed: *ptr host allocation of size 141386560 failed

### ISSUE THREAD

**Issue by ThomasTheDane** [Dhar/image-dreamer#2]
When the process reaches the 2 9 level it throws an error: 
2 9 inception_4c/output (1016, 1453, 3)
F0707 02:08:35.636888  9679 syncedmem.hpp:27] Check failed: _ptr host allocation of size 141386560 failed
*_\* Check failure stack trace: ***
Aborted

From searching around the web, people are saying to use smaller batch size, but I am unsure how you would even set that.

**Comment by Dhar** [comment]
I haven't messed with the batch size, either, but that looks like a large image and an allocation problem.  Have you tried giving the VM more memory?

**Comment by JotapePinheiro** [comment]
IndexError                                Traceback (most recent call last)
/vagrant/dreamify.py in <module>()
    111 oct_scale = float(sys.argv[6]) if len(sys.argv) > 6 else 1.4
    112 _ = deepdream(net, img, end=end_name, iter_n=iter_n, octave_n=octaves, octave_scale=oct_scale)
--> 113 savearray(_, sys.argv[2])

IndexError: list index out of range

**Comment by dirtyvader** [comment]
I had the same error, it's clearly a memory problem. I've increase v.memory to 5120 (5GB) and it's ok for 1400x1400 images. I haven't test upper sized images

**Comment by ThomasTheDane** [comment]
Yup, I found the same thing. Works on smaller images and it helps to give vm more space.

**Comment by jotapepinheiro** [comment]
![jp-3b](https://cloud.githubusercontent.com/assets/1366295/8625350/30860156-270c-11e5-8206-8fd01e20898f.jpg)
